language: php

php:
  - 5.4

env:
  - DB=mysql

before_script:
  - sudo locale-gen en_US.UTF-8
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cake_db;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cake_db_test;'; fi"
  - mkdir -p ./app/tmp/cache/models ./app/tmp/cache/persistent ./app/webroot/files/attachment
  - chmod -R 777 ./app/tmp ./app/webroot/files/attachment
  - sh -c "if [ '$PHPCS' = '1' ]; then pear channel-discover pear.cakephp.org; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then pear install --alldeps cakephp/CakePHP_CodeSniffer; fi"
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
      public \$default = array(
        'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => '0.0.0.0',
        'login' => 'travis',
        'password' => '',
        'database' => 'cake_db',
        'prefix' => '',
        'encoding' => 'utf8',
     );

    public \$test = array(
      'datasource' => 'Database/Mysql',
        'persistent' => false,
        'host' => '0.0.0.0',
        'login' => 'travis',
        'password' => '',
        'database' => 'cake_db_test',
        'prefix' => '',
        'encoding' => 'utf8',
     );
    }" > app/Config/database.php
  - (cd app; composer install)
  - (yes|./app/Console/cake schema create; exit 0)

script:
  - sh -c "./app/Console/cake test app all --stderr;"
